services:
  - type: web
    name: 12weeks
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.12"
      - key: DATABASE_URL
        fromDatabase:
          name: 12weeks-db
          property: connectionURI

databases:
  - name: 12weeks-db
    plan: free
    databaseName: twelve_weeks
